### PR TITLE
Cron validation rebased

### PR DESCRIPTION
**Pull request by jmleroux**
* Rebase of #13 
* add command tests
* rewrite command pattern check

TODO: rework cron format validation in the same PR

### CODE REVIEW

**Comment by jmleroux** [comment]
@NovikovViktor @alexandrzhulev , ready to merge ;)

**Comment by alexandrzhulev** [comment]
@jmleroux @NovikovViktor
Reviewed PR and it looks great!
Liked the solution that now the InvalidArgumentException in Cron setters is avoided (and that's the thing we also discussed with @NovikovViktor).
Having CronFormatValidators for each time property - :+1:
But to finish with this PR I'd like to rise following thoughts:
1) from one side validation is managed by annotations and from other - by validation.xml
2) validation.xml constraints are not ideal (as Regex could cause issues)

Suggestions:
1) move constraints to one place
2) add to CronFormatValidators the logic for validating upon other constraints - Regex, Not Blank 

Questions:
1) Are the suggestions above relevant?
2) Should there be added the support of non numeric values, for instance:
- */15 - to execute each fifteen minute
- 1,2,3 - to execute at 1, 2 and 3 o clock
- Jan,Feb - in January, February
(as that would make Regex rather complex and long values wouldn't fit to new form design)

What are your thoughts, guys?

**Comment by jmleroux** [comment]
> Are the suggestions above relevant?

Yep, +100.
Would you have some time to do it? I'd like to release a stable tag on our marketplace before March 20. We have an internal presentation of the marketplace and i would love to add this module to the presentation ;)

> Should there be added the support of non numeric values, for instance:
> */15 - to execute each fifteen minute
> 1,2,3 - to execute at 1, 2 and 3 o clock
> Jan,Feb - in January, February
> (as that would make Regex rather complex and long values wouldn't fit to new form design)
> What are your thoughts, guys?

Another big thumbs up!
I was thinking about that too, and i already took inspration from this repo: 
https://github.com/mtdowling/cron-expression/tree/master/src/Cron

**Comment by jmleroux** [comment]
To avoid to big PR, i propose to merge this one and start a brand new for your last ideas.
Will do it tomorrow morning unless you don't agree.

**Pull request merged**
